baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Gerald Nguyen'
theme = 'medium'

[params]
  Image = "geraldnguyen-profile.jpg"


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Lists'
pageRef = '/lists'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

