baseURL = 'https://geraldnguyen.github.io/'
languageCode = 'en-us'
title = 'Gerald Nguyen'
theme = 'medium'

[params]
  DisplayName = "Gerald Nguyen"
  Image = "geraldnguyen-profile.jpg"
  ProfileThumbnail = "geraldnguyen-profile-thumbnail.jpg"
  twitter = 'https://x.com/geraldnguyensg'
  linkedin = 'https://www.linkedin.com/in/nthehuy/'
  github = 'https://github.com/geraldnguyen'
  [params.opengraph]
    checker = 'https://globally.azurewebsites.net/api/OpenGraph'
    [params.opengraph.safeEscaped]
      "&quot;" = "\""
      "&#8211;" = "-"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/pages/about'
weight = 30

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  
  [markup.highlight]
    style = 'github'

[services]
  [services.disqus]
    shortname = 'geraldnguyen'
